dist: xenial
branches:
  only:
    - master
language: csharp
solution: ServiceMonitoringPlugin.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build ServiceMonitoringPlugin.sln
  - dotnet test -v n ServiceMonitoringPlugin.Integration.Test/ServiceMonitoringPlugin.Integration.Test.csproj
